version: '3.4'

services:
  catalog-postgresdata:
    image: postgres
    
  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile

volumes:
  postgres_catalog:

