version: '3.4'

services:
  catalog-postgresdata:
    container_name: catalog-postgresdata
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: CatalogDb
    volumes:
      -  postgres_catalog:/var/lib/postgresql/data
    ports:
      - 5432:5432