version: '3.4'

services:
  catalog-postgresdata:
    container_name: catalog-postgresdata
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: CatalogDb
    volumes:
      -  postgres_catalog:/var/lib/postgresql/data
    ports:
      - 5432:5432
  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__PostgreSQL=Host=catalog-postgresdata;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres 
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
